// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentManagement.proto

package com.CA.gRPC;

public final class EnvironmentProto {
  private EnvironmentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SwitchOnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SwitchOnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SwitchOnResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SwitchOnResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SwitchOffRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SwitchOffRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SwitchOffResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SwitchOffResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ForecastRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ForecastRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ForecastResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ForecastResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033EnvironmentManagement.proto\"&\n\017SwitchO" +
      "nRequest\022\023\n\013temperature\030\001 \001(\005\"-\n\020SwitchO" +
      "nResponse\022\031\n\021statusTemperature\030\001 \001(\005\"\'\n\020" +
      "SwitchOffRequest\022\023\n\013temperature\030\001 \001(\005\"#\n" +
      "\021SwitchOffResponse\022\016\n\006status\030\001 \001(\005\"A\n\017Fo" +
      "recastRequest\022\022\n\nmsgRequest\030\001 \001(\t\022\032\n\022msg" +
      "RequestTomorrow\030\002 \001(\t\"D\n\020ForecastRespons" +
      "e\022\023\n\013msgResponse\030\001 \001(\005\022\033\n\023msgResponseTom" +
      "orrow\030\002 \001(\0052\267\001\n\027EnvironmentMgmtServices\022" +
      "3\n\010switchOn\022\020.SwitchOnRequest\032\021.SwitchOn" +
      "Response\"\0000\001\0224\n\tswitchOff\022\021.SwitchOffReq" +
      "uest\032\022.SwitchOffResponse\"\000\0221\n\010forecast\022\020" +
      ".ForecastRequest\032\021.ForecastResponse\"\000B!\n" +
      "\013com.CA.gRPCB\020EnvironmentProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SwitchOnRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SwitchOnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SwitchOnRequest_descriptor,
        new java.lang.String[] { "Temperature", });
    internal_static_SwitchOnResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SwitchOnResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SwitchOnResponse_descriptor,
        new java.lang.String[] { "StatusTemperature", });
    internal_static_SwitchOffRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SwitchOffRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SwitchOffRequest_descriptor,
        new java.lang.String[] { "Temperature", });
    internal_static_SwitchOffResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SwitchOffResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SwitchOffResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_ForecastRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ForecastRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ForecastRequest_descriptor,
        new java.lang.String[] { "MsgRequest", "MsgRequestTomorrow", });
    internal_static_ForecastResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ForecastResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ForecastResponse_descriptor,
        new java.lang.String[] { "MsgResponse", "MsgResponseTomorrow", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
