// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentManagement.proto

package com.CA.gRPC;

/**
 * Protobuf type {@code forecastResponse}
 */
public final class forecastResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:forecastResponse)
    forecastResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use forecastResponse.newBuilder() to construct.
  private forecastResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private forecastResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new forecastResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private forecastResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            msgResponse_ = input.readInt32();
            break;
          }
          case 16: {

            msgResponseTomorrow_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.CA.gRPC.EnvironmentProto.internal_static_forecastResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.CA.gRPC.EnvironmentProto.internal_static_forecastResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.CA.gRPC.forecastResponse.class, com.CA.gRPC.forecastResponse.Builder.class);
  }

  public static final int MSGRESPONSE_FIELD_NUMBER = 1;
  private int msgResponse_;
  /**
   * <code>int32 msgResponse = 1;</code>
   * @return The msgResponse.
   */
  @java.lang.Override
  public int getMsgResponse() {
    return msgResponse_;
  }

  public static final int MSGRESPONSETOMORROW_FIELD_NUMBER = 2;
  private int msgResponseTomorrow_;
  /**
   * <code>int32 msgResponseTomorrow = 2;</code>
   * @return The msgResponseTomorrow.
   */
  @java.lang.Override
  public int getMsgResponseTomorrow() {
    return msgResponseTomorrow_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (msgResponse_ != 0) {
      output.writeInt32(1, msgResponse_);
    }
    if (msgResponseTomorrow_ != 0) {
      output.writeInt32(2, msgResponseTomorrow_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (msgResponse_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, msgResponse_);
    }
    if (msgResponseTomorrow_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, msgResponseTomorrow_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.CA.gRPC.forecastResponse)) {
      return super.equals(obj);
    }
    com.CA.gRPC.forecastResponse other = (com.CA.gRPC.forecastResponse) obj;

    if (getMsgResponse()
        != other.getMsgResponse()) return false;
    if (getMsgResponseTomorrow()
        != other.getMsgResponseTomorrow()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MSGRESPONSE_FIELD_NUMBER;
    hash = (53 * hash) + getMsgResponse();
    hash = (37 * hash) + MSGRESPONSETOMORROW_FIELD_NUMBER;
    hash = (53 * hash) + getMsgResponseTomorrow();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.CA.gRPC.forecastResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.CA.gRPC.forecastResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.CA.gRPC.forecastResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.CA.gRPC.forecastResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.CA.gRPC.forecastResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.CA.gRPC.forecastResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.CA.gRPC.forecastResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.CA.gRPC.forecastResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.CA.gRPC.forecastResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.CA.gRPC.forecastResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.CA.gRPC.forecastResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.CA.gRPC.forecastResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.CA.gRPC.forecastResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code forecastResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:forecastResponse)
      com.CA.gRPC.forecastResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.CA.gRPC.EnvironmentProto.internal_static_forecastResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.CA.gRPC.EnvironmentProto.internal_static_forecastResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.CA.gRPC.forecastResponse.class, com.CA.gRPC.forecastResponse.Builder.class);
    }

    // Construct using com.CA.gRPC.forecastResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      msgResponse_ = 0;

      msgResponseTomorrow_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.CA.gRPC.EnvironmentProto.internal_static_forecastResponse_descriptor;
    }

    @java.lang.Override
    public com.CA.gRPC.forecastResponse getDefaultInstanceForType() {
      return com.CA.gRPC.forecastResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.CA.gRPC.forecastResponse build() {
      com.CA.gRPC.forecastResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.CA.gRPC.forecastResponse buildPartial() {
      com.CA.gRPC.forecastResponse result = new com.CA.gRPC.forecastResponse(this);
      result.msgResponse_ = msgResponse_;
      result.msgResponseTomorrow_ = msgResponseTomorrow_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.CA.gRPC.forecastResponse) {
        return mergeFrom((com.CA.gRPC.forecastResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.CA.gRPC.forecastResponse other) {
      if (other == com.CA.gRPC.forecastResponse.getDefaultInstance()) return this;
      if (other.getMsgResponse() != 0) {
        setMsgResponse(other.getMsgResponse());
      }
      if (other.getMsgResponseTomorrow() != 0) {
        setMsgResponseTomorrow(other.getMsgResponseTomorrow());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.CA.gRPC.forecastResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.CA.gRPC.forecastResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int msgResponse_ ;
    /**
     * <code>int32 msgResponse = 1;</code>
     * @return The msgResponse.
     */
    @java.lang.Override
    public int getMsgResponse() {
      return msgResponse_;
    }
    /**
     * <code>int32 msgResponse = 1;</code>
     * @param value The msgResponse to set.
     * @return This builder for chaining.
     */
    public Builder setMsgResponse(int value) {
      
      msgResponse_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 msgResponse = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgResponse() {
      
      msgResponse_ = 0;
      onChanged();
      return this;
    }

    private int msgResponseTomorrow_ ;
    /**
     * <code>int32 msgResponseTomorrow = 2;</code>
     * @return The msgResponseTomorrow.
     */
    @java.lang.Override
    public int getMsgResponseTomorrow() {
      return msgResponseTomorrow_;
    }
    /**
     * <code>int32 msgResponseTomorrow = 2;</code>
     * @param value The msgResponseTomorrow to set.
     * @return This builder for chaining.
     */
    public Builder setMsgResponseTomorrow(int value) {
      
      msgResponseTomorrow_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 msgResponseTomorrow = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgResponseTomorrow() {
      
      msgResponseTomorrow_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:forecastResponse)
  }

  // @@protoc_insertion_point(class_scope:forecastResponse)
  private static final com.CA.gRPC.forecastResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.CA.gRPC.forecastResponse();
  }

  public static com.CA.gRPC.forecastResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<forecastResponse>
      PARSER = new com.google.protobuf.AbstractParser<forecastResponse>() {
    @java.lang.Override
    public forecastResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new forecastResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<forecastResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<forecastResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.CA.gRPC.forecastResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

