// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentManagement.proto

package com.CA.gRPC;

public interface forecastRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:forecastRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msgRequest = 1;</code>
   * @return The msgRequest.
   */
  java.lang.String getMsgRequest();
  /**
   * <code>string msgRequest = 1;</code>
   * @return The bytes for msgRequest.
   */
  com.google.protobuf.ByteString
      getMsgRequestBytes();

  /**
   * <code>string msgRequestTomorrow = 2;</code>
   * @return The msgRequestTomorrow.
   */
  java.lang.String getMsgRequestTomorrow();
  /**
   * <code>string msgRequestTomorrow = 2;</code>
   * @return The bytes for msgRequestTomorrow.
   */
  com.google.protobuf.ByteString
      getMsgRequestTomorrowBytes();
}
