// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentManagement.proto

package com.CA.gRPC;

public interface ForecastResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ForecastResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 msgResponse = 1;</code>
   * @return The msgResponse.
   */
  int getMsgResponse();

  /**
   * <code>int32 msgResponseTomorrow = 2;</code>
   * @return The msgResponseTomorrow.
   */
  int getMsgResponseTomorrow();
}
