// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentManagement.proto

package com.CA.gRPC;

/**
 * Protobuf type {@code ForecastRequest}
 */
public final class ForecastRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ForecastRequest)
    ForecastRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ForecastRequest.newBuilder() to construct.
  private ForecastRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ForecastRequest() {
    msgRequest_ = "";
    msgRequestTomorrow_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ForecastRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ForecastRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            msgRequest_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            msgRequestTomorrow_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.CA.gRPC.EnvironmentProto.internal_static_ForecastRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.CA.gRPC.EnvironmentProto.internal_static_ForecastRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.CA.gRPC.ForecastRequest.class, com.CA.gRPC.ForecastRequest.Builder.class);
  }

  public static final int MSGREQUEST_FIELD_NUMBER = 1;
  private volatile java.lang.Object msgRequest_;
  /**
   * <code>string msgRequest = 1;</code>
   * @return The msgRequest.
   */
  @java.lang.Override
  public java.lang.String getMsgRequest() {
    java.lang.Object ref = msgRequest_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgRequest_ = s;
      return s;
    }
  }
  /**
   * <code>string msgRequest = 1;</code>
   * @return The bytes for msgRequest.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgRequestBytes() {
    java.lang.Object ref = msgRequest_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgRequest_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSGREQUESTTOMORROW_FIELD_NUMBER = 2;
  private volatile java.lang.Object msgRequestTomorrow_;
  /**
   * <code>string msgRequestTomorrow = 2;</code>
   * @return The msgRequestTomorrow.
   */
  @java.lang.Override
  public java.lang.String getMsgRequestTomorrow() {
    java.lang.Object ref = msgRequestTomorrow_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgRequestTomorrow_ = s;
      return s;
    }
  }
  /**
   * <code>string msgRequestTomorrow = 2;</code>
   * @return The bytes for msgRequestTomorrow.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgRequestTomorrowBytes() {
    java.lang.Object ref = msgRequestTomorrow_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgRequestTomorrow_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgRequest_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgRequest_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgRequestTomorrow_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msgRequestTomorrow_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgRequest_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgRequest_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgRequestTomorrow_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msgRequestTomorrow_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.CA.gRPC.ForecastRequest)) {
      return super.equals(obj);
    }
    com.CA.gRPC.ForecastRequest other = (com.CA.gRPC.ForecastRequest) obj;

    if (!getMsgRequest()
        .equals(other.getMsgRequest())) return false;
    if (!getMsgRequestTomorrow()
        .equals(other.getMsgRequestTomorrow())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MSGREQUEST_FIELD_NUMBER;
    hash = (53 * hash) + getMsgRequest().hashCode();
    hash = (37 * hash) + MSGREQUESTTOMORROW_FIELD_NUMBER;
    hash = (53 * hash) + getMsgRequestTomorrow().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.CA.gRPC.ForecastRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.CA.gRPC.ForecastRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.CA.gRPC.ForecastRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.CA.gRPC.ForecastRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.CA.gRPC.ForecastRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.CA.gRPC.ForecastRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.CA.gRPC.ForecastRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.CA.gRPC.ForecastRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.CA.gRPC.ForecastRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.CA.gRPC.ForecastRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.CA.gRPC.ForecastRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.CA.gRPC.ForecastRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.CA.gRPC.ForecastRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ForecastRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ForecastRequest)
      com.CA.gRPC.ForecastRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.CA.gRPC.EnvironmentProto.internal_static_ForecastRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.CA.gRPC.EnvironmentProto.internal_static_ForecastRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.CA.gRPC.ForecastRequest.class, com.CA.gRPC.ForecastRequest.Builder.class);
    }

    // Construct using com.CA.gRPC.ForecastRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      msgRequest_ = "";

      msgRequestTomorrow_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.CA.gRPC.EnvironmentProto.internal_static_ForecastRequest_descriptor;
    }

    @java.lang.Override
    public com.CA.gRPC.ForecastRequest getDefaultInstanceForType() {
      return com.CA.gRPC.ForecastRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.CA.gRPC.ForecastRequest build() {
      com.CA.gRPC.ForecastRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.CA.gRPC.ForecastRequest buildPartial() {
      com.CA.gRPC.ForecastRequest result = new com.CA.gRPC.ForecastRequest(this);
      result.msgRequest_ = msgRequest_;
      result.msgRequestTomorrow_ = msgRequestTomorrow_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.CA.gRPC.ForecastRequest) {
        return mergeFrom((com.CA.gRPC.ForecastRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.CA.gRPC.ForecastRequest other) {
      if (other == com.CA.gRPC.ForecastRequest.getDefaultInstance()) return this;
      if (!other.getMsgRequest().isEmpty()) {
        msgRequest_ = other.msgRequest_;
        onChanged();
      }
      if (!other.getMsgRequestTomorrow().isEmpty()) {
        msgRequestTomorrow_ = other.msgRequestTomorrow_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.CA.gRPC.ForecastRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.CA.gRPC.ForecastRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object msgRequest_ = "";
    /**
     * <code>string msgRequest = 1;</code>
     * @return The msgRequest.
     */
    public java.lang.String getMsgRequest() {
      java.lang.Object ref = msgRequest_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgRequest_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msgRequest = 1;</code>
     * @return The bytes for msgRequest.
     */
    public com.google.protobuf.ByteString
        getMsgRequestBytes() {
      java.lang.Object ref = msgRequest_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgRequest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msgRequest = 1;</code>
     * @param value The msgRequest to set.
     * @return This builder for chaining.
     */
    public Builder setMsgRequest(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msgRequest_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string msgRequest = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgRequest() {
      
      msgRequest_ = getDefaultInstance().getMsgRequest();
      onChanged();
      return this;
    }
    /**
     * <code>string msgRequest = 1;</code>
     * @param value The bytes for msgRequest to set.
     * @return This builder for chaining.
     */
    public Builder setMsgRequestBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msgRequest_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object msgRequestTomorrow_ = "";
    /**
     * <code>string msgRequestTomorrow = 2;</code>
     * @return The msgRequestTomorrow.
     */
    public java.lang.String getMsgRequestTomorrow() {
      java.lang.Object ref = msgRequestTomorrow_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgRequestTomorrow_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msgRequestTomorrow = 2;</code>
     * @return The bytes for msgRequestTomorrow.
     */
    public com.google.protobuf.ByteString
        getMsgRequestTomorrowBytes() {
      java.lang.Object ref = msgRequestTomorrow_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgRequestTomorrow_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msgRequestTomorrow = 2;</code>
     * @param value The msgRequestTomorrow to set.
     * @return This builder for chaining.
     */
    public Builder setMsgRequestTomorrow(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msgRequestTomorrow_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string msgRequestTomorrow = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgRequestTomorrow() {
      
      msgRequestTomorrow_ = getDefaultInstance().getMsgRequestTomorrow();
      onChanged();
      return this;
    }
    /**
     * <code>string msgRequestTomorrow = 2;</code>
     * @param value The bytes for msgRequestTomorrow to set.
     * @return This builder for chaining.
     */
    public Builder setMsgRequestTomorrowBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msgRequestTomorrow_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ForecastRequest)
  }

  // @@protoc_insertion_point(class_scope:ForecastRequest)
  private static final com.CA.gRPC.ForecastRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.CA.gRPC.ForecastRequest();
  }

  public static com.CA.gRPC.ForecastRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ForecastRequest>
      PARSER = new com.google.protobuf.AbstractParser<ForecastRequest>() {
    @java.lang.Override
    public ForecastRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ForecastRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ForecastRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ForecastRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.CA.gRPC.ForecastRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

