// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OvenTemperature.proto

package com.CA.gRPC;

public interface SetPointTempOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SetPointTemp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *The temp to set the goal
   * </pre>
   *
   * <code>int32 setTemp = 1;</code>
   * @return The setTemp.
   */
  int getSetTemp();
}
