// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentManagement.proto

package com.CA.gRPC;

public interface switchOnRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:switchOnRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temperature = 1;</code>
   * @return The temperature.
   */
  int getTemperature();
}
