// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OvenTemperature.proto

package com.CA.gRPC;

public interface TempRampOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TempRamp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *The temp ramp.
   * </pre>
   *
   * <code>int32 message = 1;</code>
   * @return The message.
   */
  int getMessage();
}
