// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HomeSecuity.proto

package com.CA.gRPC;

public interface TurnOffAlarmResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TurnOffAlarmResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string statusOff = 1;</code>
   * @return The statusOff.
   */
  java.lang.String getStatusOff();
  /**
   * <code>string statusOff = 1;</code>
   * @return The bytes for statusOff.
   */
  com.google.protobuf.ByteString
      getStatusOffBytes();
}
