// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DomesticUtility.proto

package com.CA.gRPC;

public final class UtilitiesProto {
  private UtilitiesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnergyMonitorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnergyMonitorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnergyMonitorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnergyMonitorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025DomesticUtility.proto\"*\n\024EnergyMonitor" +
      "Request\022\022\n\nrequestMsg\030\001 \001(\t\",\n\025EnergyMon" +
      "itorResponse\022\023\n\013responseMsg\030\001 \001(\0052_\n\031Dom" +
      "esticUtilitiesServices\022B\n\renergyMonitor\022" +
      "\025.EnergyMonitorRequest\032\026.EnergyMonitorRe" +
      "sponse\"\0000\001B\037\n\013com.CA.gRPCB\016UtilitiesProt" +
      "oP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_EnergyMonitorRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EnergyMonitorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnergyMonitorRequest_descriptor,
        new java.lang.String[] { "RequestMsg", });
    internal_static_EnergyMonitorResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EnergyMonitorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnergyMonitorResponse_descriptor,
        new java.lang.String[] { "ResponseMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
