// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamingBidirectionalService.proto

package com.ncirl.streaming.bidirectional;

public final class BidirectionalStreamingProto {
  private BidirectionalStreamingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_streaming_BidirectionalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_streaming_BidirectionalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_streaming_BidirectionalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_streaming_BidirectionalResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#StreamingBidirectionalService.proto\022\023c" +
      "om.ncirl.streaming\"\'\n\024BidirectionalReque" +
      "st\022\017\n\007message\030\001 \001(\t\"(\n\025BidirectionalResp" +
      "onse\022\017\n\007message\030\001 \001(\t2\221\001\n\035BidirectionalS" +
      "treamingService\022p\n\023bidirectionalStream\022)" +
      ".com.ncirl.streaming.BidirectionalReques" +
      "t\032*.com.ncirl.streaming.BidirectionalRes" +
      "ponse(\0010\001BB\n!com.ncirl.streaming.bidirec" +
      "tionalB\033BidirectionalStreamingProtoP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ncirl_streaming_BidirectionalRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ncirl_streaming_BidirectionalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_streaming_BidirectionalRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_ncirl_streaming_BidirectionalResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ncirl_streaming_BidirectionalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_streaming_BidirectionalResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
