// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HomeSecurity.proto

package com.CA.gRPC;

public interface OpenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OpenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string doorID = 1;</code>
   * @return The doorID.
   */
  java.lang.String getDoorID();
  /**
   * <code>string doorID = 1;</code>
   * @return The bytes for doorID.
   */
  com.google.protobuf.ByteString
      getDoorIDBytes();
}
