// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamingClientService.proto

package com.ncirl.streaming.streamingclientservice;

public final class StreamingClientServiceProto {
  private StreamingClientServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_streaming_UnaryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_streaming_UnaryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_streaming_UnaryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_streaming_UnaryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_streaming_ClientInformation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_streaming_ClientInformation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_streaming_ServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_streaming_ServerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034StreamingClientService.proto\022\023com.ncir" +
      "l.streaming\"\034\n\014UnaryRequest\022\014\n\004name\030\001 \001(" +
      "\t\" \n\rUnaryResponse\022\017\n\007message\030\001 \001(\t\"9\n\021C" +
      "lientInformation\022\022\n\nclientName\030\001 \001(\t\022\020\n\010" +
      "dateTime\030\002 \001(\t\"!\n\016ServerResponse\022\017\n\007mess" +
      "age\030\001 \001(\t2\335\001\n\026StreamingClientService\022Y\n\020" +
      "sendUnaryRequest\022!.com.ncirl.streaming.U" +
      "naryRequest\032\".com.ncirl.streaming.UnaryR" +
      "esponse\022h\n\027streamClientInformation\022&.com" +
      ".ncirl.streaming.ClientInformation\032#.com" +
      ".ncirl.streaming.ServerResponse(\001BK\n*com" +
      ".ncirl.streaming.streamingclientserviceB" +
      "\033StreamingClientServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ncirl_streaming_UnaryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ncirl_streaming_UnaryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_streaming_UnaryRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_ncirl_streaming_UnaryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ncirl_streaming_UnaryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_streaming_UnaryResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_ncirl_streaming_ClientInformation_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ncirl_streaming_ClientInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_streaming_ClientInformation_descriptor,
        new java.lang.String[] { "ClientName", "DateTime", });
    internal_static_com_ncirl_streaming_ServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_ncirl_streaming_ServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_streaming_ServerResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
