// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamingClientService.proto

package com.ncirl.streaming.streamingclientservice;

public interface UnaryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.streaming.UnaryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
