// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DomesticUtility.proto

package com.CA.gRPC;

public interface DisableEnergyMonitorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DisableEnergyMonitorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string disableRequest = 1;</code>
   * @return The disableRequest.
   */
  java.lang.String getDisableRequest();
  /**
   * <code>string disableRequest = 1;</code>
   * @return The bytes for disableRequest.
   */
  com.google.protobuf.ByteString
      getDisableRequestBytes();
}
