// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DomesticUtility.proto

package com.CA.gRPC;

public interface EnergyMonitorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnergyMonitorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestMsg = 1;</code>
   * @return The requestMsg.
   */
  java.lang.String getRequestMsg();
  /**
   * <code>string requestMsg = 1;</code>
   * @return The bytes for requestMsg.
   */
  com.google.protobuf.ByteString
      getRequestMsgBytes();
}
