// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentManagement.proto

package com.CA.gRPC;

public interface SwitchOnResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SwitchOnResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 statusTemperature = 1;</code>
   * @return The statusTemperature.
   */
  int getStatusTemperature();
}
