// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HomeSecuity.proto

package com.CA.gRPC;

public interface TurnOnAlarmRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TurnOnAlarmRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string turnOn = 1;</code>
   * @return The turnOn.
   */
  java.lang.String getTurnOn();
  /**
   * <code>string turnOn = 1;</code>
   * @return The bytes for turnOn.
   */
  com.google.protobuf.ByteString
      getTurnOnBytes();
}
