// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DemoService.proto

package com.ncirl.demo.demoservice;

public final class DemoServiceProto {
  private DemoServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_demo_UnaryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_demo_UnaryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_demo_UnaryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_demo_UnaryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_demo_HealthCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_demo_HealthCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_demo_HealthCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_demo_HealthCheckResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021DemoService.proto\022\016com.ncirl.demo\"\037\n\014U" +
      "naryRequest\022\017\n\007request\030\001 \001(\t\"!\n\rUnaryRes" +
      "ponse\022\020\n\010response\030\001 \001(\t\"T\n\022HealthCheckRe" +
      "quest\022\023\n\013serviceName\030\001 \001(\t\022\026\n\016serviceVer" +
      "sion\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\003\"6\n\023HealthC" +
      "heckResponse\022\016\n\006status\030\001 \001(\005\022\017\n\007message\030" +
      "\002 \001(\t2\270\001\n\013DemoService\022O\n\020sendUnaryReques" +
      "t\022\034.com.ncirl.demo.UnaryRequest\032\035.com.nc" +
      "irl.demo.UnaryResponse\022X\n\013HealthCheck\022\"." +
      "com.ncirl.demo.HealthCheckRequest\032#.com." +
      "ncirl.demo.HealthCheckResponse0\001B0\n\032com." +
      "ncirl.demo.demoserviceB\020DemoServiceProto" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ncirl_demo_UnaryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ncirl_demo_UnaryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_demo_UnaryRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_com_ncirl_demo_UnaryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ncirl_demo_UnaryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_demo_UnaryResponse_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_com_ncirl_demo_HealthCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ncirl_demo_HealthCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_demo_HealthCheckRequest_descriptor,
        new java.lang.String[] { "ServiceName", "ServiceVersion", "Timestamp", });
    internal_static_com_ncirl_demo_HealthCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_ncirl_demo_HealthCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_demo_HealthCheckResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
