// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DemoService.proto

package com.ncirl.demo.demoservice;

public interface HealthCheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.demo.HealthCheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   */
  int getStatus();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
