// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DemoService.proto

package com.ncirl.demo.demoservice;

public interface UnaryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.demo.UnaryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();
}
