// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ThermostatsProto.proto

package com.CA.gRPC;

public interface BidirectionalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BidirectionalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 message = 1;</code>
   * @return The message.
   */
  int getMessage();
}
