// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ThermostatsProto.proto

package com.CA.gRPC;

public final class BidirectionalStreamingProto {
  private BidirectionalStreamingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidirectionalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidirectionalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidirectionalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidirectionalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ThermostatsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ThermostatsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ThermostatsProto.proto\"\'\n\024Bidirectiona" +
      "lRequest\022\017\n\007message\030\001 \001(\005\"(\n\025Bidirection" +
      "alResponse\022\017\n\007message\030\001 \001(\005\"+\n\023Thermosta" +
      "tsResponse\022\024\n\014responseTemp\030\001 \001(\0052i\n\035Bidi" +
      "rectionalStreamingService\022H\n\023bidirection" +
      "alStream\022\025.BidirectionalRequest\032\026.Bidire" +
      "ctionalResponse(\0010\001B,\n\013com.CA.gRPCB\033Bidi" +
      "rectionalStreamingProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BidirectionalRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BidirectionalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidirectionalRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_BidirectionalResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BidirectionalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidirectionalResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_ThermostatsResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ThermostatsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ThermostatsResponse_descriptor,
        new java.lang.String[] { "ResponseTemp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
