// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHomePing.proto

package com.CA.gRPC;

public interface ClientInformationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientInformation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientName = 1;</code>
   * @return The clientName.
   */
  java.lang.String getClientName();
  /**
   * <code>string clientName = 1;</code>
   * @return The bytes for clientName.
   */
  com.google.protobuf.ByteString
      getClientNameBytes();

  /**
   * <code>string dateTime = 2;</code>
   * @return The dateTime.
   */
  java.lang.String getDateTime();
  /**
   * <code>string dateTime = 2;</code>
   * @return The bytes for dateTime.
   */
  com.google.protobuf.ByteString
      getDateTimeBytes();
}
