// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHomeLockersProto.proto

package com.CA.gRPC;

public final class LockProto {
  private LockProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LockResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LockResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033SmartHomeLockersProto.proto\"\037\n\013LockReq" +
      "uest\022\020\n\010lockOpen\030\001 \001(\010\"\037\n\014LockResponse\022\017" +
      "\n\007message\030\001 \001(\t2;\n\014LockServices\022+\n\014Contr" +
      "olLocks\022\014.LockRequest\032\r.LockResponseB\032\n\013" +
      "com.CA.gRPCB\tLockProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LockRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LockRequest_descriptor,
        new java.lang.String[] { "LockOpen", });
    internal_static_LockResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LockResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
