// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHomeLockersProto.proto

package com.CA.gRPC;

public interface LockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool lockOpen = 1;</code>
   * @return The lockOpen.
   */
  boolean getLockOpen();
}
