// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartThermostatsProto.proto

package com.CA.gRPC;

public interface TempResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TempResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *make sure a range into range
   * </pre>
   *
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <pre>
   *answer from server
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   *answer from server
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   *keep track the temp
   * </pre>
   *
   * <code>int32 currentTemp = 3;</code>
   * @return The currentTemp.
   */
  int getCurrentTemp();
}
