// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartThermostatsProto.proto

package com.CA.gRPC;

public interface TempConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TempConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temperature = 1;</code>
   * @return The temperature.
   */
  int getTemperature();
}
