// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartThermostatsProto.proto

package com.CA.gRPC;

public interface TempUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TempUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 currentTemp = 1;</code>
   * @return The currentTemp.
   */
  int getCurrentTemp();
}
