// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartThermostatsProto.proto

package com.CA.gRPC;

public interface TempRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TempRequest)
    com.google.protobuf.MessageOrBuilder {
}
