// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ThermostatsProto.proto

package com.CA.gRPC;

public interface ThermostatsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ThermostatsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 requestTemp = 1;</code>
   * @return The requestTemp.
   */
  int getRequestTemp();
}
