// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartThermostatsProto.proto

package com.CA.gRPC;

public final class ThermostatsProto {
  private ThermostatsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TempConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TempConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TempResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TempResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TempRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TempRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TempUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TempUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033SmartThermostatsProto.proto\"!\n\nTempCon" +
      "fig\022\023\n\013temperature\030\001 \001(\005\"E\n\014TempResponse" +
      "\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\022\023\n\013cu" +
      "rrentTemp\030\003 \001(\005\"\r\n\013TempRequest\"!\n\nTempUp" +
      "date\022\023\n\013currentTemp\030\001 \001(\0052m\n\023Temperature" +
      "Services\022,\n\016setTemperature\022\013.TempConfig\032" +
      "\r.TempResponse\022(\n\tcheckTemp\022\014.TempReques" +
      "t\032\013.TempUpdate(\001B!\n\013com.CA.gRPCB\020Thermos" +
      "tatsProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TempConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TempConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TempConfig_descriptor,
        new java.lang.String[] { "Temperature", });
    internal_static_TempResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TempResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TempResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "CurrentTemp", });
    internal_static_TempRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TempRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TempRequest_descriptor,
        new java.lang.String[] { });
    internal_static_TempUpdate_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_TempUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TempUpdate_descriptor,
        new java.lang.String[] { "CurrentTemp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
