// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHomePing.proto

package com.CA.gRPC;

public interface UnaryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UnaryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
