// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHomePing.proto

package com.CA.gRPC;

public interface UnaryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UnaryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
