// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DomesticUtility.proto

package com.CA.gRPC;

public interface DisableEnergyMonitorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DisableEnergyMonitorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string disableResponse = 1;</code>
   * @return The disableResponse.
   */
  java.lang.String getDisableResponse();
  /**
   * <code>string disableResponse = 1;</code>
   * @return The bytes for disableResponse.
   */
  com.google.protobuf.ByteString
      getDisableResponseBytes();
}
