// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DomesticUtility.proto

package com.CA.gRPC;

public interface EnergyMonitorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnergyMonitorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *this should return a number that represent the energy consume (as stream)
   * </pre>
   *
   * <code>int32 responseMsg = 1;</code>
   * @return The responseMsg.
   */
  int getResponseMsg();
}
