// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DomesticUtility.proto

package com.CA.gRPC;

/**
 * <pre>
 *------- TURN ON -------
 * </pre>
 *
 * Protobuf type {@code EnergyMonitorRequest}
 */
public final class EnergyMonitorRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EnergyMonitorRequest)
    EnergyMonitorRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EnergyMonitorRequest.newBuilder() to construct.
  private EnergyMonitorRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EnergyMonitorRequest() {
    requestMsg_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EnergyMonitorRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EnergyMonitorRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            requestMsg_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.CA.gRPC.UtilitiesProto.internal_static_EnergyMonitorRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.CA.gRPC.UtilitiesProto.internal_static_EnergyMonitorRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.CA.gRPC.EnergyMonitorRequest.class, com.CA.gRPC.EnergyMonitorRequest.Builder.class);
  }

  public static final int REQUESTMSG_FIELD_NUMBER = 1;
  private volatile java.lang.Object requestMsg_;
  /**
   * <code>string requestMsg = 1;</code>
   * @return The requestMsg.
   */
  @java.lang.Override
  public java.lang.String getRequestMsg() {
    java.lang.Object ref = requestMsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestMsg_ = s;
      return s;
    }
  }
  /**
   * <code>string requestMsg = 1;</code>
   * @return The bytes for requestMsg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestMsgBytes() {
    java.lang.Object ref = requestMsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestMsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestMsg_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestMsg_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestMsg_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestMsg_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.CA.gRPC.EnergyMonitorRequest)) {
      return super.equals(obj);
    }
    com.CA.gRPC.EnergyMonitorRequest other = (com.CA.gRPC.EnergyMonitorRequest) obj;

    if (!getRequestMsg()
        .equals(other.getRequestMsg())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUESTMSG_FIELD_NUMBER;
    hash = (53 * hash) + getRequestMsg().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.CA.gRPC.EnergyMonitorRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.CA.gRPC.EnergyMonitorRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.CA.gRPC.EnergyMonitorRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.CA.gRPC.EnergyMonitorRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.CA.gRPC.EnergyMonitorRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.CA.gRPC.EnergyMonitorRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.CA.gRPC.EnergyMonitorRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.CA.gRPC.EnergyMonitorRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.CA.gRPC.EnergyMonitorRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.CA.gRPC.EnergyMonitorRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.CA.gRPC.EnergyMonitorRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.CA.gRPC.EnergyMonitorRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.CA.gRPC.EnergyMonitorRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *------- TURN ON -------
   * </pre>
   *
   * Protobuf type {@code EnergyMonitorRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EnergyMonitorRequest)
      com.CA.gRPC.EnergyMonitorRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.CA.gRPC.UtilitiesProto.internal_static_EnergyMonitorRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.CA.gRPC.UtilitiesProto.internal_static_EnergyMonitorRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.CA.gRPC.EnergyMonitorRequest.class, com.CA.gRPC.EnergyMonitorRequest.Builder.class);
    }

    // Construct using com.CA.gRPC.EnergyMonitorRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requestMsg_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.CA.gRPC.UtilitiesProto.internal_static_EnergyMonitorRequest_descriptor;
    }

    @java.lang.Override
    public com.CA.gRPC.EnergyMonitorRequest getDefaultInstanceForType() {
      return com.CA.gRPC.EnergyMonitorRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.CA.gRPC.EnergyMonitorRequest build() {
      com.CA.gRPC.EnergyMonitorRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.CA.gRPC.EnergyMonitorRequest buildPartial() {
      com.CA.gRPC.EnergyMonitorRequest result = new com.CA.gRPC.EnergyMonitorRequest(this);
      result.requestMsg_ = requestMsg_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.CA.gRPC.EnergyMonitorRequest) {
        return mergeFrom((com.CA.gRPC.EnergyMonitorRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.CA.gRPC.EnergyMonitorRequest other) {
      if (other == com.CA.gRPC.EnergyMonitorRequest.getDefaultInstance()) return this;
      if (!other.getRequestMsg().isEmpty()) {
        requestMsg_ = other.requestMsg_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.CA.gRPC.EnergyMonitorRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.CA.gRPC.EnergyMonitorRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object requestMsg_ = "";
    /**
     * <code>string requestMsg = 1;</code>
     * @return The requestMsg.
     */
    public java.lang.String getRequestMsg() {
      java.lang.Object ref = requestMsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestMsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string requestMsg = 1;</code>
     * @return The bytes for requestMsg.
     */
    public com.google.protobuf.ByteString
        getRequestMsgBytes() {
      java.lang.Object ref = requestMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string requestMsg = 1;</code>
     * @param value The requestMsg to set.
     * @return This builder for chaining.
     */
    public Builder setRequestMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestMsg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string requestMsg = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestMsg() {
      
      requestMsg_ = getDefaultInstance().getRequestMsg();
      onChanged();
      return this;
    }
    /**
     * <code>string requestMsg = 1;</code>
     * @param value The bytes for requestMsg to set.
     * @return This builder for chaining.
     */
    public Builder setRequestMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestMsg_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:EnergyMonitorRequest)
  }

  // @@protoc_insertion_point(class_scope:EnergyMonitorRequest)
  private static final com.CA.gRPC.EnergyMonitorRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.CA.gRPC.EnergyMonitorRequest();
  }

  public static com.CA.gRPC.EnergyMonitorRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EnergyMonitorRequest>
      PARSER = new com.google.protobuf.AbstractParser<EnergyMonitorRequest>() {
    @java.lang.Override
    public EnergyMonitorRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EnergyMonitorRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EnergyMonitorRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EnergyMonitorRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.CA.gRPC.EnergyMonitorRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

