// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OvenTemperature.proto

package com.CA.gRPC;

public final class OvenTempRampProto {
  private OvenTempRampProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SetPointTemp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SetPointTemp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TempRamp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TempRamp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025OvenTemperature.proto\"\037\n\014SetPointTemp\022" +
      "\017\n\007setTemp\030\001 \001(\005\"\033\n\010TempRamp\022\017\n\007message\030" +
      "\001 \001(\0052?\n\017TemperatureRamp\022,\n\014SendTempData" +
      "\022\r.SetPointTemp\032\t.TempRamp\"\0000\001B\"\n\013com.CA" +
      ".gRPCB\021OvenTempRampProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SetPointTemp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SetPointTemp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SetPointTemp_descriptor,
        new java.lang.String[] { "SetTemp", });
    internal_static_TempRamp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TempRamp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TempRamp_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
