// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentManagement.proto

package com.CA.gRPC;

public interface SwitchOffRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SwitchOffRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string temperature = 1;</code>
   * @return The temperature.
   */
  java.lang.String getTemperature();
  /**
   * <code>string temperature = 1;</code>
   * @return The bytes for temperature.
   */
  com.google.protobuf.ByteString
      getTemperatureBytes();
}
