// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHomeProto.proto

package com.CA.gRPC;

public interface LightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool lightOn = 1;</code>
   * @return The lightOn.
   */
  boolean getLightOn();
}
