// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ThermostatsProto.proto

package com.CA.gRPC;

public interface ThermostatsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ThermostatsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 responseTemp = 1;</code>
   * @return The responseTemp.
   */
  int getResponseTemp();
}
