// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ThermostatsProto.proto

package com.CA.gRPC;

public interface WeatherForecastRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WeatherForecastRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
